Repository MITgcm/MITgcm, pull requests merged in 2021-06, with the labels that each got.

#467 optimise store directives in seaice_growth_adx
  doc/tag-index
  pkg/seaice/seaice_growth_adx.F
  verification/offline_exf_seaice/results/output_adm.txt
Labels: adjoint

#476 avoid recomputation warnings and recomputations in ggl90_calc
  doc/tag-index
  pkg/ggl90/ggl90_calc.F
Labels: adjoint

#482 ctrl/autodiff cleanup follow-up
  doc/tag-index
  pkg/autodiff/tamc.h
  pkg/shelfice/shelfice_thermodynamics.F
  verification/1D_ocean_ice_column/code_ad/tamc.h
  verification/OpenAD/code_ad/tamc.h
  verification/OpenAD/code_ad_singlelayer/tamc.h
  verification/bottom_ctrl_5x5/code_ad/tamc.h
  verification/global_oce_biogeo_bling/code_ad/tamc.h
  verification/global_ocean.90x40x15/code_ad/tamc.h
  verification/global_ocean.cs32x15/code_ad/tamc.h
  verification/global_ocean_ebm/code_ad/tamc.h
  verification/global_with_exf/code_ad/tamc.h
  verification/halfpipe_streamice/code_ad/tamc.h
  verification/isomip/code_ad/tamc.h
  verification/lab_sea/code_ad/tamc.h
  verification/offline_exf_seaice/code_ad/tamc.h
  verification/tutorial_dic_adjoffline/code_ad/tamc.h
  verification/tutorial_global_oce_biogeo/code_ad/tamc.h
  verification/tutorial_global_oce_optim/code_ad/tamc.h
  verification/tutorial_tracer_adjsens/code_ad/tamc.h
Labels: adjoint

#486 add `_building_the_manual` reference
  doc/contributing/contributing.rst
Labels: manual

#488 Fix incorrect array subscript order
  doc/tag-index
  pkg/ecco/cost_gencost_bpv4.F
  pkg/ecco/cost_gencost_sstv4.F
Labels: adjoint

#493 Fix previous modif in CPP_EEMACROS.h (from PR #487)
  eesupp/inc/CPP_EEMACROS.h
Labels: bug

#492 Ctrl cleanup followup-2
  doc/tag-index
  model/src/salt_integrate.F
  model/src/temp_integrate.F
  pkg/bling/bling_bio.F
  pkg/bling/bling_light.F
  pkg/bling/bling_mixedlayer.F
  pkg/bling/bling_sgs.F
  pkg/ctrl/ctrl_map_ini_gentim2d.F
  pkg/ebm/ebm_area_t.F
  pkg/ebm/ebm_atmosphere.F
  pkg/ebm/ebm_zonalmean.F
  pkg/exf/exf_radiation.F
  pkg/longstep/longstep_thermodynamics.F
  pkg/obcs/obcs_calc_stevens.F
  pkg/obcs/obcs_sponge.F
  pkg/openad/the_model_main.F
  pkg/pp81/pp81_ri_number.F
  pkg/seaice/seaice_calc_lhs.F
  pkg/seaice/seaice_calc_strainrates.F
  pkg/seaice/seaice_diffusion.F
  pkg/seaice/seaice_do_ridging.F
  pkg/seaice/seaice_freedrift.F
  pkg/seaice/seaice_jfnk.F
  pkg/seaice/seaice_oceandrag_coeffs.F
  pkg/seaice/seaice_prepare_ridging.F
  pkg/streamice/streamice_vel_phi.F
  pkg/streamice/streamice_vel_phistage.F
  pkg/streamice/streamice_vel_solve_openad.F
  verification/obcs_ctrl/code_ad/OBCS_OPTIONS.h
Labels: adjoint

#494 Fix spurious recomputations and storing in seaice_solve4temp.F
  doc/tag-index
  pkg/seaice/seaice_solve4temp.F
Labels: adjoint
